### ISSUE TITLE
Deleted test cases are still present in the tsuite file

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#10]
Create a test suite and add two test cases (T1 and T2) to it
Delete test case T2 and generate code.  The following error is displayed:

![image](https://user-images.githubusercontent.com/367073/231952429-bca4c887-743c-4e2c-9405-02a07be0fe98.png)

Fix

- Before deleting a test case, make sure it is not in any test suite.   If it is, list the test suites it is in and prompt the user if they wish to remove from all test suite and delete?

**Comment by brogreenmoon** [comment]
Confirmed.  If a test case is in a Test Suite and you try to delete it you now see:

![image](https://user-images.githubusercontent.com/114720205/233905588-9a3c693d-a189-4166-8fd0-921c1fe8e72d.png)

If you click "Delete" the test case is removed from the test suite and code can be generated without issue
