### ISSUE TITLE
Prevent a page definition from being saved when required fields are missing values

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/ide#108]
Prevent a page definition from being saved when required fields are missing values.  The problem right now is that there is no validation, which in turn means codegen fails and it's quite difficult to relate that failure back to the source of the problem.

For example, when a Click action is performed but no page element is defined:

![image](https://github.com/rockmelonqa/ide/assets/114720205/9f955940-10cd-473d-845d-fd30a54d3a3d)

the following codegen error is displayed:

![image](https://github.com/rockmelonqa/ide/assets/114720205/146082aa-ce7b-411f-b820-2e354edf6cf1)

When I click Save the app should check that all mandatory fields (based on whether the action works against a page element or not) have values, and if they don't, then highlight those missing fields and prevent the page from being saved.  Something like this:

![image](https://github.com/rockmelonqa/ide/assets/114720205/681d4d58-702b-4881-b514-0027381c9da7)

**Comment by veebs** [comment]
Will be imlemented with #118
