### ISSUE TITLE
The old file name is not being deleted when a file is renamed

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#11]

**Comment by brogreenmoon** [comment]
This is working as expected now.  I renamed a page definition and a test case without issue:

![image](https://user-images.githubusercontent.com/114720205/232379893-b378f0ef-e3fd-4c01-84ed-9151bc716890.png)

![image](https://user-images.githubusercontent.com/114720205/232379923-6320a2aa-9134-4fcc-a83f-1fc03f49733e.png)

![image](https://user-images.githubusercontent.com/114720205/232380017-b5340ff5-0d8b-4849-9a2b-2ff53b052c0c.png)

![image](https://user-images.githubusercontent.com/114720205/232380029-232a2d4b-0b73-48cd-84ae-953399ef7057.png)

**Comment by brogreenmoon** [comment]
Confirmed.  I renamed a page definition and a test case without issue:

![image](https://user-images.githubusercontent.com/114720205/233545626-861aa9ea-31c5-4e5f-beaa-d68aaa599070.png)

![image](https://user-images.githubusercontent.com/114720205/233545703-97690381-2ece-4e91-9283-2542bf8f26ea.png)

![image](https://user-images.githubusercontent.com/114720205/233545720-7f615d69-bb13-4297-95f7-a0bf4caee165.png)
