### ISSUE TITLE
Enable/disable the Page and Element fields depending on the whether the Action applies to page elements

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#13]
When the selected action applies to page elements enable the Page and Element fields.  When it is a method that does not act on a page element clear and disable the Page and Element fields, because they are not relevant fields for that Action.

**Page Element Actions**

Clear
Click
Click Popup
Input
Input By Code
Select Option
Verify Attribute
Verify Has Text
Verify Has Value
Verify Is Editable
Verify Is Hidden
Verify Is ReadOnly
Verify Is Visible

**Pageless Actions**

Close Popup
Delay
Go To URL
Run Code
Verify Title
Verify Title Contain
Verify URL

**Comment by hanglequan1991** [comment]
Hi @veebs , @quockhanh ,
Please help me review this PR https://github.com/rockmelonqa/ide/pull/54

**Comment by brogreenmoon** [comment]
Two things:

1. I think we need to not show the "Please select" labels for Page and Element when the action does not act on a page element. 

The colouring is so similar it's hard to tell which ones are read-only and which ones aren't, e.g. they're read-only/not required for the "Go To URL" but are editable and required for "Click":

![image](https://github.com/rockmelonqa/ide/assets/114720205/8aad7fa4-35ad-4788-bb81-ffee19a4bc14)

Maybe like this:

![image](https://github.com/rockmelonqa/ide/assets/114720205/da7ba61f-09a4-4d0d-8fd5-daaa9b067837)

which brings me onto point 2:

2. Oops, Verify URL should have been in the pageless section.  It doesn't require a page or element!

**Comment by hanglequan1991** [comment]
Hi @veebs , @quockhanh ,
I've created a PR for hiding page and element field to pageless action

https://github.com/rockmelonqa/ide/pull/110

**Comment by quockhanh** [comment]
We need to add following action to pageless action list:

Verify Title
Verify Title Contain
Verify URL

**Comment by brogreenmoon** [comment]
We need the grid editor to get this back to looking decent again, but the functionality is correct as specified here:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/b0552d80-29e3-4664-b973-8652ddcab56f)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/47633f7a-638b-417c-832a-71176bf274d0)
