### ISSUE TITLE
The page-definition and test-cases folders are minimised after the first page definition/test case is created

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#14]
The page-definition and test-cases folders are minimised after the first page definition/test case is created.

1. Create a new project
2. Add a page definition, mypage.page and hit Enter

The page-definition folder is minimised and needs to be clicked twice to expand it again.

It should stay expanded after a page definition is added.  Note that this defect typically can't be reproduced if you add a second page definition to the folder.

**Comment by hanglequan1991** [comment]
Hi @veebs ,
I've created a PR for this issue 
https://github.com/rockmelonqa/ide/pull/37

**Comment by brogreenmoon** [comment]
![image](https://user-images.githubusercontent.com/114720205/233545233-d462d225-a770-498b-9c6f-8e92263b696d.png)

![image](https://user-images.githubusercontent.com/114720205/233545322-d96461b4-14bf-4def-a0b5-d30663394ac9.png)

**Comment by brogreenmoon** [comment]
This problem is happening again!

**Comment by quockhanh** [comment]
I cannot reproduce bug at my local (still work well with 0.2.1 installer)

Anyone else find try

**Comment by hanglequan1991** [comment]
I did reproduce this issue 1 time, but after that I can't reproduce again.

**Comment by brogreenmoon** [comment]
Close.  I can't reproduce this problem in 0.2.2
