### ISSUE TITLE
Move the test case Action column so it's the left-most column

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#15]
Right now the test case columns are:

![image](https://user-images.githubusercontent.com/367073/231953706-d2ee5cd8-d607-4376-95ed-3bfa440ff7db.png)

Change it so the order is Action - Page - Element - Data.

**Comment by hanglequan1991** [comment]
Hi @veebs  please help me review this PR https://github.com/rockmelonqa/ide/pull/36
