### ISSUE TITLE
Verify Attribute usage, plus it causes the codegen process to fail

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#16]
Usage of VerifyAttribute gives the codegen error below.

The intended usage of this action is to check that an attribute of a page element has a certain value, by entering the attribute name=attribute value key/value pair in the data field.  For example, setting the data field to "spellcheck=false" or "enabled=true".  

![image](https://user-images.githubusercontent.com/367073/231953973-91acc261-f8a5-43d6-8a92-e0963b639e93.png)

**Comment by brogreenmoon** [comment]
Resolved.  Verify Attribute is working:

![image](https://user-images.githubusercontent.com/114720205/234155423-81d35b62-4fbe-4091-9601-9f8484e8a50c.png)

generates:

![image](https://user-images.githubusercontent.com/114720205/234155448-9339edad-26a6-4b37-81ae-a0ae7123af36.png)

and executes without error.
