### ISSUE TITLE
Verify IsHidden usage, plus it causes the codegen process to fail

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#17]
"Verify IsHidden" causes codegen to fail.

Maybe we should rename it to "Verify Visible", then the data field is changed to a dropdown where you can select True or False to check whether an element is visible or hidden?

![image](https://user-images.githubusercontent.com/367073/231954089-5586e2cf-30ef-47fc-8977-abfbe414ac9f.png)

**Comment by vothaison** [comment]
Hi @veebs 
We should add a verify for IsVisible. Playwright has 2 separate Expects: ToBeHiddenAsync() and ToBeHiddenAsync, ToBeVisibleAsync. We should have 2 separete actions for those.

**Comment by brogreenmoon** [comment]
Confirmed that "Verify Is Visible" and "Verify Is Hidden" are working and this is their implementation:

![image](https://user-images.githubusercontent.com/114720205/234154489-3d99f204-4eec-4e23-b318-20149dd1c74d.png)
