### ISSUE TITLE
Verify Title causes the codegen process to fail

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#18]
![image](https://user-images.githubusercontent.com/367073/231954143-980eef61-9e98-436d-a78a-22a9f97e1a25.png)

**Comment by brogreenmoon** [comment]
Resolved.  The following project builds and executes without error:

![image](https://user-images.githubusercontent.com/114720205/234152534-216d4a84-72d4-4bf3-b0c4-772c2733e348.png)

![image](https://user-images.githubusercontent.com/114720205/234152548-bbccc89d-0364-480c-af2e-f0c99d0ba5f3.png)

![image](https://user-images.githubusercontent.com/114720205/234152565-8cfd7851-70ac-49fd-a369-49ae4473506a.png)
