### ISSUE TITLE
Usage of "Input By Code" causes the codegen process to fail

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#20]

**Comment by vothaison** [comment]
Hi @veebs 
The "Input By Code" action requires user to provide data as a string in a double quotes, and escaped manually
![image](https://user-images.githubusercontent.com/11172436/232190854-1e1c9afa-7a7a-4f63-92b8-c84a09c777b3.png)
![image](https://user-images.githubusercontent.com/11172436/232190868-62e101a0-b6e3-4026-9f73-c0a3244b7bf1.png)

**Comment by brogreenmoon** [comment]
Confirmed that this is working successfully.  I searched for today's date in Google:

![image](https://user-images.githubusercontent.com/114720205/233564303-85a1a144-9ece-45e6-8b12-e5e46547ba99.png)

![image](https://user-images.githubusercontent.com/114720205/233564343-086a7252-fbe1-4e65-9580-37f41b8bf7ef.png)
