### ISSUE TITLE
Add support for TestId 

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#21]
See https://playwrightsolutions.com/getbytestid/

The TestId field will default to "data-testid".  Websites don't have to use this convention, e.g. X web site use "data-test".  Users need to be able to configure the TestId attribute that applies to the application-under-test.  Without this setting they are required to revert back to using Xpath expressions, e.g. FindBy = Xpath, Locator = //a[@data-test, "continue-button"], rather than FindBy = TestId, Locator = continue-button.

**Project Setting**

Add to rmproj and Advance settings dialog a new field called "testIdAttributeName".  Default to "data-testid" if the field is empty

**Page Def**
Add new Find By type called "Test Id"

**Code Gen**
For the Find By type called "Test Id", generate: `page.getByTestId({data value})`

**Comment by brogreenmoon** [comment]
Implemented.  Given this test id attribute:

![image](https://github.com/rockmelonqa/ide/assets/114720205/7f29989e-74f1-4cb3-b1bb-d42c2d47bb33)

And these page definitions:

![image](https://github.com/rockmelonqa/ide/assets/114720205/a960c406-3074-41a8-9028-e1521325e51d)

The following code is generated:

![image](https://github.com/rockmelonqa/ide/assets/114720205/1d0823f1-5309-40fd-a52c-becd54894837)

And the locators are found at run-time.
