### ISSUE TITLE
Add a "Close Project" File menu option

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#24]
There's currently no way to simply close a project.

When "Close Project..." is selected check for any pending changes first, then close the project and direct the user to the Home page.

**Comment by hanglequan1991** [comment]
Hi @quockhanh ,
Please help me review this PR 
https://github.com/rockmelonqa/ide/pull/125
Thanks,

**Comment by brogreenmoon** [comment]
Implemented.  Confirmed that the "Close Project" menu option appears:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/96049e59-5be0-4c6c-9339-73783e6ee734)

And that a confirmation dialog is shown when there are pending changes:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/d91b7b12-1c3c-48d8-88cd-c3eb87a82333)

Verified the system behaviour when Yes, No and Cancel are clicked.

Confirmed that the Home page is displayed when a project is closed.
