### ISSUE TITLE
Make the Element Name field focused after "Add Element" is clicked

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#25]
The Element Name field should be selected/focused after "Add Element" is clicked.  Right now you have to click into the field yourself to add the details for the element.

![image](https://user-images.githubusercontent.com/367073/231955344-ac90dbc8-6623-43af-84b0-0118e095c1ca.png)

**Comment by hanglequan1991** [comment]
Hi @veebs , @quockhanh 
Please help me review this PR https://github.com/rockmelonqa/ide/pull/119

**Comment by quockhanh** [comment]
> Hi @veebs , @quockhanh Please help me review this PR #119

Need other solution rather than settimeout

**Comment by hanglequan1991** [comment]
Hi @quockhanh ,
I've created another PR https://github.com/rockmelonqa/ide/pull/121
Thanks,

**Comment by quockhanh** [comment]
> Hi @quockhanh , I've created another PR #121 Thanks,

setting autoFocus on onMount or Init,  make the page focuses to last element when onload
Skip this ticket until figure out better solution

**Comment by brogreenmoon** [comment]
Done.  Confirmed when "Add Element", "Add Comment", "+" and "<add comment speech bubble>" is clicked.

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/11519355-ea3d-49a6-aa9b-bbf7d1d3d9d5)
