### ISSUE TITLE
Add the ability to copy/clone Page Definition and Test Case items

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#4]
![image](https://user-images.githubusercontent.com/367073/231949540-9d1f31d4-b70f-477b-a487-40e784987a79.png)

After copy, new Guid should be created

**Comment by quockhanh** [comment]
I suggest using 'Clone' label
If we use Copy, then we should support Paste.  User may paste somewhere else (copy 'page' but paste outside of page-definition folder)
Clone mean, copy then paste right there

**Comment by brogreenmoon** [comment]
Implemented.  I cloned a page-definition and a test-case, then added the cloned test case to my test suite, then generated the code and executed both tests:

![image](https://github.com/rockmelonqa/ide/assets/114720205/9cec6f37-4de6-4cfe-9bd9-0d1c6c25641b)

![image](https://github.com/rockmelonqa/ide/assets/114720205/e034b99a-3633-4ada-85e1-e5169111bff0)
