### ISSUE TITLE
Prevent a page definition from being saved if an element name contains spaces or special characters

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/ide#46]
If an element name contains spaces or special characters then flag it visually:

![image](https://user-images.githubusercontent.com/114720205/233543021-1add6963-9702-4803-b286-937e17a933e0.png)

and prevent the page from being saved until the error is resolved.

The Codegen error you get when this happens is:

![image](https://user-images.githubusercontent.com/114720205/233543262-f4367727-5649-4227-853e-9be7289fba95.png)

Only when you try to build the project in Visual Studio is the cause of the issue apparent:

![image](https://user-images.githubusercontent.com/114720205/233543465-9d82b464-172e-4521-8c2c-38412a10c8ca.png)

**Comment by hanglequan1991** [comment]
hi @quockhanh  please help me review this PR https://github.com/rockmelonqa/ide/pull/120

**Comment by veebs** [comment]
Will be imlemented with #118
