### ISSUE TITLE
Add support for test routine

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#5]

**Comment by quockhanh** [comment]
Backend logic has not been implemented yet

**Comment by brogreenmoon** [comment]
Implemented and functional, although it needs the editor changes in #118 and the support for multiple datasets in #143 to meet the goal of test routines being truly data-driven, in the sense that you should be able to define a single test case and be able to run it across multiple datasets.

The main thing we need to add is a test case -level view of the data scenarios it covers.  This is complicated by the test case potentially calling many test routines, with each of those test routines having different numbers of datasets.  The test case then needs to manage the dataset combos and provide a visualisation of each data scenario that applies.  Ticket #118 discusses these requirements.
