### ISSUE TITLE
Change the "Delete Test Case" dialog message

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/ide#56]
Change it to "This test case is being used by the following test suites.  Do you want to remove it?".

![image](https://user-images.githubusercontent.com/114720205/233904899-6a88fe6a-faf2-4c59-8011-ee929c105b8d.png)

**Comment by hanglequan1991** [comment]
Hi @quockhanh ,
Please help me review this PR https://github.com/rockmelonqa/ide/pull/122

**Comment by brogreenmoon** [comment]
Done:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/55cb1f0a-0ca8-4a02-ba28-1a2a1355c20e)
