### ISSUE TITLE
Add support for custom code

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#6]
Copy code from custom code folder in to the generated code folder.  

In this way, when you execute Run Code, you can call static methods or instance a class, etc...

**Test Case**
Add a custom code file 

```
public static class MyTestClass
{
   public static void MyTestMethod() {
     // Write hello world to log file
   }
}
```

Then in a test case, execute Run Code `MyTestClass.MyTestMethod()`

**Comment by hanglequan1991** [comment]
hi @quockhanh , @veebs , 
Please help me review this PR https://github.com/rockmelonqa/ide/compare/rockmelonqa:main...hanglequan1991:issue/6?expand=1

**Comment by brogreenmoon** [comment]
Implemented:

![image](https://github.com/rockmelonqa/ide/assets/114720205/aa03c579-1017-40b4-8729-cde43bb0a235)

![image](https://github.com/rockmelonqa/ide/assets/114720205/f124bdd3-5e26-4988-a771-aef8025fd529)
