### ISSUE TITLE
Issue with "Find By Relative" usage and that it causes codegen to fail

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/ide#60]
I'm not sure what the usage of the "Relative" type is when locating page elements.  We need to discuss it.

It currently causes codegen to fail as well:

![image](https://user-images.githubusercontent.com/114720205/233925124-f091715c-0c81-411c-9938-432926ec7c80.png)

![image](https://user-images.githubusercontent.com/114720205/233925150-e6d23fb3-233d-4506-941d-c8223d4c31af.png)

**Comment by brogreenmoon** [comment]
I tried this usage:

![image](https://user-images.githubusercontent.com/114720205/233940309-0c419c6b-13c0-4187-a3e7-ecc11ab4717e.png)

but it gave:

![image](https://user-images.githubusercontent.com/114720205/233940362-90018e71-430b-4a7a-8c52-a837cb08c3e2.png)

**Comment by vothaison** [comment]
Hi @brogreenmoon 

The usage of findBy 'Relative' is like this:

![image](https://user-images.githubusercontent.com/11172436/234614244-78202f43-e74c-4945-8f0b-0a4c0f461b0a.png)

Basically we are locate the nested element

The use case could be like this 

![image](https://user-images.githubusercontent.com/11172436/234614954-2c2b9d97-a4f6-47fd-a8c3-b187277f1140.png)

in which case the Child element is resolved to the element on line 11, not the one on line 13.

It is just what we have in the test-tool project (https://dev.azure.com/zapcentral/test-tool/_git/test-tool), which may or may not be relevant in our the IDE project.

**Comment by brogreenmoon** [comment]
Hi @vothaison,

Your example uses CSS - should it also work for usages like the following?

![image](https://github.com/rockmelonqa/ide/assets/114720205/30894d61-496d-4c52-992f-84defb9141e8)

**Comment by vothaison** [comment]
Hi @vothaison 
I think I will assume that if the parent element is located by Xpath, then the child element will also by located by Xpath => Child element has the same Locator to the parent element.

**Comment by quockhanh** [comment]
cc @brogreenmoon

**Comment by veebs** [comment]
Can we split the `Relative` action into 2:
- RelativeCss = {elementName}:{css locator}
- RelativeXPath = {elementName}:{xpath locator}
?

**Comment by brogreenmoon** [comment]
Confirmed usage of Relative XPath:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/0fc27687-9e70-4928-a503-644ea3fe06a4)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/c4c4dec3-0bc9-4729-855b-1908edc23c67)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/197ede80-9b69-4e5b-8a2d-da6b9b90d220)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/ef98a9f2-f1e7-48cf-b343-cf1f0d47d115)

**Comment by brogreenmoon** [comment]
Confirmed usage of Relative CSS:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/b597de06-836e-4cdc-bed1-08940bf22c8b)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/38188354-0e36-4258-8dd9-528d17ceb7cb)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/fac279e0-fc0a-4915-be35-09074100717f)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/3d70a859-b30e-4b05-b247-20efb7e8b54e)
