### ISSUE TITLE
Code gen check for unique object names when generating code

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#7]
Check for unique page, test case, test routine and test suite names

For example:
Admin/Raw Data $1.page -> Admin_RawData1Page
Admin/Raw Data 1$.page -> Admin_RawData1Page

Show error "Admin/Raw Data $1.page and Admin/Raw Data 1$.page resolve to the same name page class name.  Please change one of the files to make the names unique.

**Comment by brogreenmoon** [comment]
I'm trying to recreate this scenario, but codegen is failing.  Project files attached.

[Google.zip](https://github.com/rockmelonqa/ide/files/11447157/Google.zip)

![image](https://github.com/rockmelonqa/ide/assets/114720205/10d7d025-ce3d-4ea2-be21-ddc4efa9c143)

**Comment by quockhanh** [comment]
@vothaison  please take a look  (it was failed testing)

**Comment by brogreenmoon** [comment]
Resolved:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/149f23ef-f369-47b0-a101-c2b948f0eafa)
