### ISSUE TITLE
Add the ability to insert a line item directly after an existing item

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#8]
![image](https://user-images.githubusercontent.com/114720205/232378879-6777820a-7bc9-44d2-80b6-10a7c05e1e4c.png)

Change the order of Actions so it is Add, Delete, Up and Down

**Comment by hanglequan1991** [comment]
Hi @veebs , @quockhanh 
Please help me review this PR https://github.com/rockmelonqa/ide/pull/50

**Comment by brogreenmoon** [comment]
![image](https://user-images.githubusercontent.com/114720205/233903577-a99c4273-3c50-4fa2-933a-ccf90ba117ea.png)

![image](https://user-images.githubusercontent.com/114720205/233903682-8e6aab33-01e4-42b4-af56-c330f3677c34.png)

n/a for test suites.  I think.

**Comment by brogreenmoon** [comment]
"Add Step" is done.  Please also add a second "Add Comment" action.

**Comment by hanglequan1991** [comment]
> "Add Step" is done. Please also add a second "Add Comment" action.

Hi @brogreenmoon , Please help me verify `Add Comment` action, this function has been included by this change.

**Comment by brogreenmoon** [comment]
![image](https://user-images.githubusercontent.com/114720205/236652065-d017605b-5ddb-4795-900a-5a86cf994138.png)

**Comment by brogreenmoon** [comment]
Implemented:

![image](https://github.com/rockmelonqa/ide/assets/114720205/7265df7c-50fb-4857-9cd7-3af4ff228efe)
