### ISSUE TITLE
Do not start with maximized window 

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/ide#9]
Currently, on start up, the window is always maximized.

On exit, is it possible to save the window size and style in to user settings.

When it is opened next, resume the window in user settings.

If no user settings exists, open in normal window mode rather than maximized.

**Comment by hanglequan1991** [comment]
Hi @veebs, @quockhanh 
Please help me review this PR https://github.com/rockmelonqa/ide/pull/51
I've applied `electron-store` to store the window size

**Comment by brogreenmoon** [comment]
Resolved.  If the IDE is maximised on saved then the next time the app is run it is maximised.

If the app is not maximised the next time it is run it is not maximised, like so:

![image](https://user-images.githubusercontent.com/114720205/233905162-d4d30c0d-77b7-4865-9732-9dbb3b30f502.png)
